package com.hazerta.pojos;
// Generated 11-jun-2018 19:54:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String nif;
     private Provincias provincias;
     private String nombre;
     private String apellidos;
     private String direccion;
     private Integer telefono;
     private String email;
     private boolean eliminado;
     private Set usuarioses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String nif, Provincias provincias, String nombre, String apellidos, boolean eliminado) {
        this.nif = nif;
        this.provincias = provincias;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.eliminado = eliminado;
    }
    public Clientes(String nif, Provincias provincias, String nombre, String apellidos, String direccion, Integer telefono, String email, boolean eliminado, Set usuarioses) {
       this.nif = nif;
       this.provincias = provincias;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.eliminado = eliminado;
       this.usuarioses = usuarioses;
    }
   
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


