package com.hazerta.pojos;
// Generated 11-jun-2018 19:54:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private byte idPerfil;
     private String nombre;
     private Set usuarioses = new HashSet(0);

    public Perfiles() {
    }

	
    public Perfiles(byte idPerfil, String nombre) {
        this.idPerfil = idPerfil;
        this.nombre = nombre;
    }
    public Perfiles(byte idPerfil, String nombre, Set usuarioses) {
       this.idPerfil = idPerfil;
       this.nombre = nombre;
       this.usuarioses = usuarioses;
    }
   
    public byte getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(byte idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


