package com.hazerta.pojos;
// Generated 11-jun-2018 19:54:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private int idProvincia;
     private String nombre;
     private Set clienteses = new HashSet(0);

    public Provincias() {
    }

	
    public Provincias(int idProvincia, String nombre) {
        this.idProvincia = idProvincia;
        this.nombre = nombre;
    }
    public Provincias(int idProvincia, String nombre, Set clienteses) {
       this.idProvincia = idProvincia;
       this.nombre = nombre;
       this.clienteses = clienteses;
    }
   
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


