package com.hazerta.pojos;
// Generated 11-jun-2018 19:54:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String logo;
     private Set articuloses = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(int idProveedor, String nombre) {
        this.idProveedor = idProveedor;
        this.nombre = nombre;
    }
    public Proveedores(int idProveedor, String nombre, String logo, Set articuloses) {
       this.idProveedor = idProveedor;
       this.nombre = nombre;
       this.logo = logo;
       this.articuloses = articuloses;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }




}


